---
title: "GlitterApp Presentation"
author: "Rinnette N. Ramdhanie"
date: "24 February 2020"
output: 
  ioslides_presentation:
          css: pres.css
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(ggplot2)
```

## Glitters Diamond Brokerage (GDB) presents <span style="font-weight:bold; color:#12809E">GlitterApp</span>

GlitterApp calculates a minimum price that will be paid by GDB, for any diamond, given Carat, Cut, Colour and Clarity.

### How does <span style="font-weight:bold; color:#12809E">GlitterApp</span> work?

- Enter carat, cut, colour and clarity in the form provided
- Send a printscreen of the resulting price to the email address provided
- A representative of GDB will contact you to make arrangements to authenticate the stone
- Once authenticated, payment is guaranteed in 24 hours


## Advantages of using <span style="font-weight:bold; color:#12809E">GlitterApp</span>

- Quickly get the price you will be offered with no waiting or delays
- Price provided is the minumum price guaranteed
- Prices are negotiable
- Payment is made within 24 hours of the stone being authenticated
- GDB has 35 convenient locations


## Information to be entered

<font size="4">
**Carat**  
The minimum carats that can be entered is `r min(diamonds$carat)` and the maximum is `r max(diamonds$carat)`

**Cut**  
The Cut values that can be entered are `r unique(diamonds$cut)` where Ideal is the best and Fair is the worst.

**Colour**  
Colours range from `r unique(diamonds[order(diamonds$color), ]$color)` where

- D, E and F are *colourless* with D being the best
- G, H, I are J are *near colourless* with J being the worst 

**Clarity**  
Clarity takes the values `r levels(diamonds$clarity)` where I1 is the worst and IF the best.
</font>

<font size="2">Note that R expressions were used to retrieve the values for caret, cut, color and clarity for this slide.  Check the Rmd file in the github repo for code.</font>

## Where to find <span style="font-weight:bold; color:#12809E">GlitterApp</span>
Link to GlitterApp: <a href="https://niala.shinyapps.io/GlitterApp/">www.glitters.com/GlitterApp</a>

Hope to hear from you soon!
